CONNECTION_STRING="mongodb+srv://javbarrios89:mediasense@clubstride.nh1tclt.mongodb.net/"

DB_URL="postgresql://neondb_owner:npg_QR7pUMEb8lnm@ep-hidden-mud-a6bxzi52-pooler.us-west-2.aws.neon.tech/neondb?sslmode=require"

MAILERSEND_API_KEY="mlsn.27532cddb53b1b9f94008c4a0548e1c9236f4a8e1d3074dfb312569fbecd5c90"
