CONNECTION_STRING="mongodb+srv://javbarrios89:mediasense@clustersense.nh1tclt.mongodb.net/"

DB_URL="postgresql://neondb_owner:npg_Wnoe53VzhGbs@ep-hidden-mud-a6bxzi52-pooler.us-west-2.aws.neon.tech/neondb?sslmode=require"

MAILERSEND_API_KEY="mlsn.12738f0dde9468d6168a430e091254c71cd3c1e5cd4c0e24c39050e5a3dee184"
